package trinagleAngles;


/**
* trinagleAngles/TriangleAnglesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from angles.idl
* Thursday, January 3, 2019 10:05:40 AM EET
*/

public abstract class TriangleAnglesPOA extends org.omg.PortableServer.Servant
 implements trinagleAngles.TriangleAnglesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("computeAngles", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // trinagleAngles/TriangleAngles/computeAngles
       {
         double x1 = in.read_double ();
         double y1 = in.read_double ();
         double x2 = in.read_double ();
         double y2 = in.read_double ();
         double x3 = in.read_double ();
         double y3 = in.read_double ();
         String $result = null;
         $result = this.computeAngles (x1, y1, x2, y2, x3, y3);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:trinagleAngles/TriangleAngles:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TriangleAngles _this() 
  {
    return TriangleAnglesHelper.narrow(
    super._this_object());
  }

  public TriangleAngles _this(org.omg.CORBA.ORB orb) 
  {
    return TriangleAnglesHelper.narrow(
    super._this_object(orb));
  }


} // class TriangleAnglesPOA
