package trinagleAngles;

/**
* trinagleAngles/TriangleAnglesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from angles.idl
* Thursday, January 3, 2019 10:05:40 AM EET
*/

public final class TriangleAnglesHolder implements org.omg.CORBA.portable.Streamable
{
  public trinagleAngles.TriangleAngles value = null;

  public TriangleAnglesHolder ()
  {
  }

  public TriangleAnglesHolder (trinagleAngles.TriangleAngles initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = trinagleAngles.TriangleAnglesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    trinagleAngles.TriangleAnglesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return trinagleAngles.TriangleAnglesHelper.type ();
  }

}
