package trinagleAngles;


/**
* trinagleAngles/TriangleAngles.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from angles.idl
* Thursday, January 3, 2019 10:05:40 AM EET
*/

public interface TriangleAngles extends TriangleAnglesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TriangleAngles
