package trinagleAngles;


/**
* trinagleAngles/TriangleAnglesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from angles.idl
* Thursday, January 3, 2019 10:05:40 AM EET
*/

public interface TriangleAnglesOperations 
{
  String computeAngles (double x1, double y1, double x2, double y2, double x3, double y3);
} // interface TriangleAnglesOperations
