package trinagleAngles;


/**
* trinagleAngles/TriangleAnglesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from angles.idl
* Thursday, January 3, 2019 10:05:40 AM EET
*/

abstract public class TriangleAnglesHelper
{
  private static String  _id = "IDL:trinagleAngles/TriangleAngles:1.0";

  public static void insert (org.omg.CORBA.Any a, trinagleAngles.TriangleAngles that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static trinagleAngles.TriangleAngles extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (trinagleAngles.TriangleAnglesHelper.id (), "TriangleAngles");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static trinagleAngles.TriangleAngles read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TriangleAnglesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, trinagleAngles.TriangleAngles value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static trinagleAngles.TriangleAngles narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof trinagleAngles.TriangleAngles)
      return (trinagleAngles.TriangleAngles)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      trinagleAngles._TriangleAnglesStub stub = new trinagleAngles._TriangleAnglesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static trinagleAngles.TriangleAngles unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof trinagleAngles.TriangleAngles)
      return (trinagleAngles.TriangleAngles)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      trinagleAngles._TriangleAnglesStub stub = new trinagleAngles._TriangleAnglesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
